"""SOS Services - Data Models"""

from datetime import datetime
from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field


class EventType(str, Enum):
    WEATHER = "weather"
    FIRE = "fire"
    EMERGENCY = "emergency"
    TRAFFIC = "traffic"
    EVENT = "event"


class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class HazardLevel(str, Enum):
    NONE = "none"
    WATCH = "watch"
    WARNING = "warning"
    DANGER = "danger"
    EXTREME = "extreme"


class Location(BaseModel):
    lat: float = Field(..., ge=-90, le=90)
    lng: float = Field(..., ge=-180, le=180)


class GeoEvent(BaseModel):
    """Unified event schema — all data sources normalize into this."""

    id: str
    type: EventType
    category: str                  # e.g. "wildfire", "flood_warning", "concert"
    title: str
    description: Optional[str] = None
    location: Location
    radius_km: Optional[float] = None  # affected area radius
    severity: Severity = Severity.LOW
    source: str                    # e.g. "ipma", "firms", "prociv"
    start_time: datetime
    end_time: Optional[datetime] = None
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    active: bool = True


class HazardAlert(BaseModel):
    """Generated by the correlation engine when overlapping risks are detected."""

    id: str
    level: HazardLevel
    title: str
    description: str
    location: Location
    radius_km: float
    contributing_events: List[str]  # list of GeoEvent IDs
    recommended_action: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class MapLayer(BaseModel):
    """Represents a toggleable layer on the map."""

    id: str
    name: str
    type: EventType
    visible: bool = True
    color: str
    icon: str
    event_count: int = 0


class SystemStatus(BaseModel):
    """Health status of data adapters."""

    adapter: str
    healthy: bool
    last_fetch: Optional[datetime] = None
    event_count: int = 0
    error: Optional[str] = None
